<?php
/**
 * @var \app\modules\actions\models\Action $model
 */
return array(
    'attributes'=>array(
        'class'=>'well',
		'enctype'=>'multipart/form-data',
    ),
    'elements'=>array(
		'm_title'=>array(
            'type'=>'text',
            'maxlength'=>100,
            'attributes'=>array(
                'class'=>'span6',
            ),
        ),
        'file'=>array(
			'type'=>'file',
			'visible'=>true,
	        'attributes'=>array(
		        'label'=>'Изображение'.($model->hasFile('s') ? CHtml::link('Удалить текущее изображение', array('deleteImage', 'id'=>$model->id), array('class'=>'delete-img')) : ''),
	        ),
		),
        'short_text'=>array(
            'type'=>\Siix::module('base')->textEditor,
            'hint'=>'Клавиша <strong>Enter</strong> создает новый абзац.<br />Чтобы просто перейти на новую строку, используйте сочетание клавиш <strong>Shift+Enter</strong>.',
            'htmlOptions'=>array(
                'style'=>'width: 100%; height: 350px;',
            ),
        ),
        'text'=>array(
            'type'=>\Siix::module('base')->textEditor,
            'hint'=>'Клавиша <strong>Enter</strong> создает новый абзац.<br />Чтобы просто перейти на новую строку, используйте сочетание клавиш <strong>Shift+Enter</strong>.',
            'htmlOptions'=>array(
                'style'=>'width: 100%; height: 350px;',
            ),
        ),
        'active'=>array(
            'type'=>'checkbox',
        ),
        'finish_time'=>array(
            'type'=>'\sii\web\widgets\timepicker\TimePicker',
            'options'=>array(
                'dateFormat'=>'yy-mm-dd',
                'showAnim'=>'slideDown',
            ),
            'htmlOptions'=>array(
                'class'=>'span2',
            ),
        ),
        'page'=>array(
            'type'=>'form',
            'elements'=>array(
                'title'=>array(
                    'type'=>'text',
                    'maxlength'=>255,
                    'attributes'=>array(
                        'class'=>'span6',
                    ),
                ),
                'orderPosition'=>array(
                    'type'=>'\sii\web\widgets\PositionSelector',
                    'titleField'=>'title',
                ),
                'seo'=>array(
                    'type'=>'form',
                    'visible'=>user()->checkAccess('seo'),
                    'skipEmpty'=>true,
                    'elements'=>array(
                        'title'=>array(
                            'type'=>'text',
                            'maxlength'=>255,
                            'attributes'=>array(
                                'class'=>'span6',
                            ),
                        ),
                        'description'=>array(
                            'type'=>'text',
                            'attributes'=>array(
                                'class'=>'span6',
                            ),
                        ),
                        'keywords'=>array(
                            'type'=>'text',
                            'hint'=>'Теги страницы через запятую.',
                            'attributes'=>array(
                                'class'=>'span6',
                            ),
                        ),
                        'header'=>array(
                            'type'=>'text',
                            'maxlength'=>255,
                            'attributes'=>array(
                                'class'=>'span6',
                            ),
                        ),
                    ),
                ),
                'url'=>array(
                    'type'=>'form',
                    'skipEmpty'=>true,
                    'elements'=>array(
                        'slug'=>array(
                            'type'=>'text',
                            'maxlength'=>100,
                            'attributes'=>array(
                                'class'=>'span6',
                            ),
                        ),
                    ),
                ),
            ),
        ),
    ),
    'buttons'=>array(
        'save'=>array(
            'type'=>'submit',
            'label'=>'Сохранить',
            'attributes'=>array(
                'class'=>'btn btn-large',
            ),
        ),
    ),
);